"""Workspace schema normalization — split by concern."""

from .agents_tools import (
    workspace_default_agents,
    workspace_default_tools,
    normalize_workspace_tool,
    normalize_workspace_tools,
    normalize_workspace_agent,
    normalize_workspace_agents,
    normalize_global_tool_definition,
    normalize_global_tool_definitions,
    normalize_global_agent_definition,
    normalize_global_agent_definitions,
    default_tool_definition_by_id,
    default_agent_preset_for,
    backfill_default_tool_definitions,
    default_agent_required_tool_ids,
    workspace_required_default_tool_ids,
    backfill_default_agent_tools,
)

from .chat import (
    normalize_workspace_context_reflection,
    normalize_workspace_chat_message,
    normalize_workspace_chat,
    make_workspace_chat_message,
    workspace_agent_name,
    workspace_source_brief,
    build_workspace_chat_reply,
    workspace_agent_by_id,
    workspace_tool_index,
    workspace_agent_focus_node,
    build_workspace_agent_debug,
)

from .nodes import (
    workspace_node_definition,
    workspace_node_kinds_for_source,
    should_upgrade_default_workflow_chain,
    recommended_node_assignment,
    workspace_prior_output_keys,
    finalize_agent_executable_nodes,
    build_recommended_handler,
    workspace_node_default_config,
    make_workspace_node,
    normalize_workspace_nodes,
    normalize_workspace_links,
    sync_workspace_nodes_with_overview,
)

from .recipe import (
    normalize_workspace_recipe,
    normalize_workspace_handler,
    normalize_workspace_runtime,
    normalize_workspace_model,
    normalize_workspace_inputs,
    clean_workspace_config_default,
    normalize_source_mode,
    infer_source_mode_from_inputs,
    source_type_for_chain,
    workspace_input_source_summary,
)

from .templates import (
    workflow_template_sort_key,
    collect_template_agent_ids,
    collect_template_tool_ids,
    normalize_workflow_template,
    normalize_workflow_template_version_history,
    workflow_template_version_record,
    build_default_workflow_templates,
    build_template_snapshot,
    workflow_template_snapshot_diff,
    normalize_workspace_instance_from_template,
)

__all__ = [
    "backfill_default_agent_tools",
    "backfill_default_tool_definitions",
    "build_default_workflow_templates",
    "build_recommended_handler",
    "build_template_snapshot",
    "workflow_template_snapshot_diff",
    "build_workspace_agent_debug",
    "build_workspace_chat_reply",
    "clean_workspace_config_default",
    "collect_template_agent_ids",
    "collect_template_tool_ids",
    "default_agent_preset_for",
    "default_agent_required_tool_ids",
    "default_tool_definition_by_id",
    "finalize_agent_executable_nodes",
    "infer_source_mode_from_inputs",
    "make_workspace_chat_message",
    "make_workspace_node",
    "normalize_global_agent_definition",
    "normalize_global_agent_definitions",
    "normalize_global_tool_definition",
    "normalize_global_tool_definitions",
    "normalize_source_mode",
    "normalize_workflow_template",
    "normalize_workflow_template_version_history",
    "normalize_workspace_agent",
    "normalize_workspace_agents",
    "normalize_workspace_chat",
    "normalize_workspace_chat_message",
    "normalize_workspace_context_reflection",
    "normalize_workspace_handler",
    "normalize_workspace_inputs",
    "normalize_workspace_instance_from_template",
    "normalize_workspace_links",
    "normalize_workspace_model",
    "normalize_workspace_nodes",
    "normalize_workspace_recipe",
    "normalize_workspace_runtime",
    "normalize_workspace_tool",
    "normalize_workspace_tools",
    "recommended_node_assignment",
    "should_upgrade_default_workflow_chain",
    "source_type_for_chain",
    "sync_workspace_nodes_with_overview",
    "workflow_template_sort_key",
    "workflow_template_version_record",
    "workspace_agent_by_id",
    "workspace_agent_focus_node",
    "workspace_agent_name",
    "workspace_default_agents",
    "workspace_default_tools",
    "workspace_input_source_summary",
    "workspace_node_default_config",
    "workspace_node_definition",
    "workspace_node_kinds_for_source",
    "workspace_prior_output_keys",
    "workspace_required_default_tool_ids",
    "workspace_source_brief",
    "workspace_tool_index",
]
