"""Auto-split from constants.py — workspace_contracts."""

from __future__ import annotations

from pathlib import Path
from typing import Any

WORKSPACE_NODE_IO_CONTRACTS: dict[str, dict[str, Any]] = {
    "source.repo": {
        "inputs": ["目标", "仓库 URL", "分支 / 提交"],
        "output_key": "source_repo",
        "evidence": "仓库来源、版本和启动目标",
    },
    "source.paper": {
        "inputs": ["目标", "论文 / 资料", "参考线索"],
        "output_key": "paper_context",
        "evidence": "论文、任务和候选实现线索",
    },
    "source.idea": {
        "inputs": ["目标描述", "约束", "成功标准"],
        "output_key": "idea_brief",
        "evidence": "需求、约束和验收标准",
    },
    "research.search": {
        "inputs": ["source_context", "论文 / 资料", "参考线索"],
        "output_key": "research_brief",
        "evidence": "候选 repo、issue、论文和资料结论",
    },
    "repo.clone": {
        "inputs": ["source_repo", "repo_url", "repo_ref"],
        "output_key": "repo_checkout",
        "evidence": "本地仓库路径、分支和提交",
    },
    "path.resolve": {
        "inputs": ["repo_checkout", "工作目录", "数据 / 输出线索"],
        "output_key": "path_map",
        "evidence": "工作目录、数据目录、输出目录和日志目录",
    },
    "repo.inspect": {
        "inputs": ["repo_checkout", "path_map"],
        "output_key": "repo_profile",
        "output_format": "json",
        "evidence": "入口脚本、依赖文件、默认参数和结果目录",
    },
    "dataset.find": {
        "inputs": ["paper_context", "repo_profile", "数据集 / 路径线索"],
        "output_key": "dataset_profile",
        "output_format": "json",
        "evidence": "数据集名称、本地路径候选和结构要求",
    },
    "env.infer": {
        "inputs": ["repo_profile", "path_map"],
        "output_key": "env_requirements",
        "output_format": "json",
        "evidence": "Python/CUDA/依赖文件和安装建议",
    },
    "env.prepare": {
        "inputs": ["env_requirements", "setup_command"],
        "output_key": "env_ready",
        "evidence": "环境名、安装命令、依赖检查结果",
    },
    "gpu.allocate": {
        "inputs": ["env_ready", "run_profile", "GPU 快照"],
        "output_key": "gpu_allocation",
        "evidence": "目标服务器、GPU 编号、显存和调度策略",
    },
    "run.command": {
        "inputs": ["repo_profile", "dataset_profile", "env_ready", "gpu_allocation"],
        "output_key": "run_result",
        "evidence": "任务 ID、命令、日志、退出状态和运行路径",
    },
    "artifact.collect": {
        "inputs": ["run_result", "path_map"],
        "output_key": "artifact_manifest",
        "evidence": "日志、指标、模型文件和复跑命令",
    },
    "eval.report": {
        "inputs": ["artifact_manifest", "run_result"],
        "output_key": "evaluation_report",
        "output_format": "json",
        "evidence": "指标、结论、失败原因和下一步建议",
    },
}

AGENT_NODE_DEFAULT_INPUT_MAPPINGS: dict[str, dict[str, str]] = {
    "research.search": {
        "source_context": "$prev.output",
        "论文 / 资料": "$input.paper_urls",
        "参考线索": "$input.references",
    },
    "repo.inspect": {
        "repo_checkout": "$context.outputs.repo_checkout",
        "path_map": "$context.outputs.path_map",
    },
    "dataset.find": {
        "paper_context": "$input.paper_urls",
        "repo_profile": "$context.outputs.repo_profile",
        "数据集 / 路径线索": "$input.references",
    },
    "env.infer": {
        "repo_profile": "$context.outputs.repo_profile",
        "path_map": "$context.outputs.path_map",
    },
    "eval.report": {
        "artifact_manifest": "$context.outputs.artifact_manifest",
        "run_result": "$context.outputs.run_result",
    },
    "path.resolve": {
        "repo_checkout": "$context.outputs.repo_checkout",
        "工作目录": "$input.workspace_dir",
        "数据 / 输出线索": "$input.references",
    },
    "artifact.collect": {
        "run_result": "$context.outputs.run_result",
        "path_map": "$context.outputs.path_map",
    },
}

DEFAULT_WORKSPACE_TOOLS: list[dict[str, Any]] = [
    {
        "id": "workflow.plan",
        "label": "工作流规划",
        "category": "workflow",
        "capability": "write",
        "description": "拆分目标、编排节点、补交接说明。",
        "enabled": True,
    },
    {
        "id": "workflow.edit",
        "label": "工作流编辑",
        "category": "workflow",
        "capability": "control",
        "description": "新增、移动、删除或重排工作流节点。",
        "enabled": True,
    },
    {
        "id": "web.search",
        "label": "网络检索",
        "category": "research",
        "capability": "read",
        "description": "搜索论文、repo、issue、文档和公开说明。",
        "enabled": True,
    },
    {
        "id": "repo.search",
        "label": "仓库搜寻",
        "category": "research",
        "capability": "read",
        "description": "围绕关键字找候选仓库、star、issue 和镜像。",
        "enabled": True,
    },
    {
        "id": "repo.clone",
        "label": "仓库克隆",
        "category": "repo",
        "capability": "execute",
        "description": "把仓库拉到目标工作目录。",
        "enabled": True,
    },
    {
        "id": "repo.read",
        "label": "仓库阅读",
        "category": "repo",
        "capability": "read",
        "description": "读取源码、README、配置和入口说明。",
        "enabled": True,
    },
    {
        "id": "repo.inspect",
        "label": "仓库检查",
        "category": "repo",
        "capability": "read",
        "description": "扫描依赖、入口、默认参数和输出目录。",
        "enabled": True,
    },
    {
        "id": "path.resolve",
        "label": "路径解析",
        "category": "path",
        "capability": "read",
        "description": "确认工作目录、数据目录、日志目录和输出路径。",
        "enabled": True,
    },
    {
        "id": "dataset.find",
        "label": "数据集发现",
        "category": "data",
        "capability": "read",
        "description": "从论文、README、线索和本地数据盘定位数据集。",
        "enabled": True,
    },
    {
        "id": "file.browse",
        "label": "文件浏览",
        "category": "file",
        "capability": "read",
        "description": "浏览本地或远端目录树。",
        "enabled": True,
    },
    {
        "id": "file.read",
        "label": "文件预览",
        "category": "file",
        "capability": "read",
        "description": "读取文本、日志和配置文件的片段。",
        "enabled": True,
    },
    {
        "id": "dir.scan",
        "label": "目录扫描",
        "category": "host",
        "capability": "read",
        "description": "查看可用工作目录、挂载盘和项目目录。",
        "enabled": True,
    },
    {
        "id": "host.exec",
        "label": "主机执行计划",
        "category": "host",
        "capability": "execute",
        "description": "通过受控 job 队列执行目标主机检查或命令，保留日志和停止入口。",
        "enabled": True,
    },
    {
        "id": "gpu.inspect",
        "label": "GPU 探测",
        "category": "gpu",
        "capability": "read",
        "description": "查询可用显卡、利用率、显存和温度。",
        "enabled": True,
    },
    {
        "id": "gpu.allocate",
        "label": "GPU 候选",
        "category": "gpu",
        "capability": "read",
        "description": "给出 GPU 调度候选；真正占用由工作流任务处理。",
        "enabled": True,
    },
    {
        "id": "env.inspect",
        "label": "环境检查",
        "category": "env",
        "capability": "read",
        "description": "检查 conda、python3、tmux、rsync 等依赖。",
        "enabled": True,
    },
    {
        "id": "env.infer",
        "label": "环境推断",
        "category": "env",
        "capability": "read",
        "description": "从依赖文件、README 和运行脚本推断安装步骤。",
        "enabled": True,
    },
    {
        "id": "env.prepare",
        "label": "环境准备",
        "category": "env",
        "capability": "execute",
        "description": "创建或激活 conda / venv 并安装依赖。",
        "enabled": True,
    },
    {
        "id": "env.create",
        "label": "环境创建",
        "category": "env",
        "capability": "execute",
        "description": "初始化新的 Python 环境与基础依赖。",
        "enabled": True,
    },
    {
        "id": "job.run",
        "label": "任务提交包",
        "category": "run",
        "capability": "execute",
        "description": "通过受控 job 队列提交运行任务，并同步 workspace run 记录。",
        "enabled": True,
    },
    {
        "id": "job.stop",
        "label": "任务停止",
        "category": "run",
        "capability": "control",
        "description": "停止正在运行的任务或进程。",
        "enabled": True,
    },
    {
        "id": "job.reorder",
        "label": "队列重排",
        "category": "run",
        "capability": "control",
        "description": "调整等待中任务的优先顺序。",
        "enabled": True,
    },
    {
        "id": "execution.package",
        "label": "执行包读取",
        "category": "run",
        "capability": "read",
        "description": "读取当前执行包、调度目标、缺口、回填建议和复跑脚本摘要。",
        "enabled": True,
    },
    {
        "id": "log.read",
        "label": "日志读取",
        "category": "log",
        "capability": "read",
        "description": "读取任务日志、输出和 tmux 片段。",
        "enabled": True,
    },
    {
        "id": "artifact.read",
        "label": "产物读取",
        "category": "artifact",
        "capability": "read",
        "description": "查看项目产物、指标和中间结果。",
        "enabled": True,
    },
    {
        "id": "artifact.collect",
        "label": "产物收集",
        "category": "artifact",
        "capability": "read",
        "description": "收集日志、指标、模型文件和复跑命令。",
        "enabled": True,
    },
    {
        "id": "artifact.write",
        "label": "产物写入",
        "category": "artifact",
        "capability": "write",
        "description": "写入整理后的结论、摘要和检查点。",
        "enabled": True,
    },
    {
        "id": "report.write",
        "label": "结果报告",
        "category": "artifact",
        "capability": "write",
        "description": "输出评估报告、对比摘要和下一步建议。",
        "enabled": True,
    },
    {
        "id": "notify.user",
        "label": "用户通知",
        "category": "notify",
        "capability": "write",
        "description": "把关键结论、失败原因或待确认项推回给用户。",
        "enabled": True,
    },
    {
        "id": "chat.write",
        "label": "项目对话",
        "category": "chat",
        "capability": "write",
        "description": "把自然语言输入写入项目上下文与对话历史。",
        "enabled": True,
    },
    {
        "id": "schedule.plan",
        "label": "调度规划",
        "category": "workflow",
        "capability": "write",
        "description": "记录定时运行、批量 sweep 和重复执行计划。",
        "enabled": True,
    },
]


DEFAULT_WORKSPACE_AGENTS: list[dict[str, Any]] = [
    {
        "id": "planner",
        "name": "Planner",
        "role": "planner",
        "prompt": "把用户目标整理成可执行节点和审批点。",
        "tools": ["workflow.edit", "workflow.plan", "execution.package", "artifact.write", "chat.write"],
        "provider_profile_id": "",
    },
    {
        "id": "researcher",
        "name": "Researcher",
        "role": "researcher",
        "prompt": "检索论文、repo、issue、文档和候选方案。",
        "tools": ["web.search", "repo.search", "dataset.find", "artifact.read", "artifact.write"],
        "provider_profile_id": "",
    },
    {
        "id": "repo-scout",
        "name": "Repo Scout",
        "role": "repo_scout",
        "prompt": "理解仓库结构、依赖、入口和运行方式。",
        "tools": ["repo.clone", "repo.read", "repo.inspect", "path.resolve", "file.read", "artifact.write", "workflow.edit"],
        "provider_profile_id": "",
    },
    {
        "id": "gpu-scout",
        "name": "GPU Scout",
        "role": "gpu_scout",
        "prompt": "找可用显卡、判断忙碌程度并给出可运行的主机。",
        "tools": ["gpu.inspect", "gpu.allocate", "host.exec", "dir.scan"],
        "provider_profile_id": "",
    },
    {
        "id": "env-builder",
        "name": "Env Builder",
        "role": "env_builder",
        "prompt": "准备环境、检查依赖并整理安装步骤。",
        "tools": ["env.inspect", "env.infer", "env.prepare", "env.create", "host.exec", "file.read", "workflow.edit", "artifact.write"],
        "provider_profile_id": "",
    },
    {
        "id": "runner",
        "name": "Runner",
        "role": "runner",
        "prompt": "把运行配方转换为实际任务并跟踪输出。",
        "tools": ["execution.package", "job.run", "job.stop", "job.reorder", "gpu.allocate", "log.read"],
        "provider_profile_id": "",
    },
    {
        "id": "evaluator",
        "name": "Evaluator",
        "role": "evaluator",
        "prompt": "解析结果、指标、产出文件和回归结论。",
        "tools": ["execution.package", "artifact.collect", "artifact.read", "log.read", "report.write", "notify.user"],
        "provider_profile_id": "",
    },
    {
        "id": "watcher",
        "name": "Watcher",
        "role": "watcher",
        "prompt": "监控运行异常、卡住的任务和日志里的错误信号。",
        "tools": ["log.read", "job.stop", "notify.user", "artifact.write"],
        "provider_profile_id": "",
    },
    {
        "id": "reporter",
        "name": "Reporter",
        "role": "reporter",
        "prompt": "把过程、结果和下一步建议整理成可分享的总结。",
        "tools": ["execution.package", "artifact.read", "artifact.write", "report.write", "chat.write"],
        "provider_profile_id": "",
    },
]
